name: Build tvbox-Swift iOS IPA
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

      - name: 修改项目部署目标 iOS 17，规避iOS18 SDK依赖
        run: >
          plutil -replace LABEL -string IPHONEOS_DEPLOYMENT_TARGET tvbox.xcodeproj/project.pbxproj

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ github.sha }}

      - name: Xcode Clean
        run: >
          xcodebuild clean -project tvbox.xcodeproj -scheme tvbox -destination generic/platform=iOS

      - name: Archive
        run: >
          xcodebuild archive -project tvbox.xcodeproj -scheme tvbox -destination generic/platform=iOS -archivePath tvboxSwift.xcarchive PRODUCT_BUNDLE_IDENTIFIER=com.test.tvboxswift SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Generate exportOptions.plist
        run: >
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string><key>signingCertificate</key><string></string><key>provisioningProfile</key><string></string><key>bundleIdentifier</key><string>com.test.tvboxswift</string></dict></plist>' > exportOptions.plist

      - name: Export IPA
        run: >
          xcodebuild -exportArchive -archivePath tvboxSwift.xcarchive -exportPath ./output -exportOptionsPlist exportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: tvbox-swift-ipa
          path: ./output/*.ipa
          retention-days: 7
